In [1]:
import numpy as np
from itertools import product

In [3]:
xx = np.load("TM_test.npy")

In [4]:
len(xx)

2

In [18]:
xx[0][:,:,:,0][1,0,0]

45260226.0

In [5]:
def test(xx):
    for mu in xx:
        print(np.argmax([mu[1,1,1,0],mu[1,2,0,0],mu[2,1,0,0]]))
# test(xx)

In [1]:
import code_for_bohao as cfb

Individual :  1
10.166616916656494
False
Individual :  2
12.07315182685852
False
Individual :  3
10.23523235321045
True
Individual :  4
10.8580641746521
False
Individual :  5
12.503694534301758
False
Individual :  6
12.262425422668457
False
Individual :  7
8.9329674243927
True
Individual :  8
13.395765542984009
False
Individual :  9
15.174124240875244
False
Individual :  10
13.102978944778442
False


In [7]:
cfb.Label_twoHits, cfb.Label_oneHit

([0, 0, 1, 0, 0, 0, 1, 0, 0, 0], [0, 0, 1, 0, 0, 0, 1, 0, 0, 0])

In [11]:
cfb.TH

[array([[ 458.5],
        [1463. ],
        [3307. ]]), array([[ 562. ],
        [1527. ],
        [3645.5]])]

In [8]:
cfb.TH_oneHit, cfb.TH_twoHits

([array([ 999.5, 3666.5, 5000. ]),
  array([1521.5, 3703.5, 5000. ]),
  array([ 458.5, 1463. , 3307. ]),
  array([ 840. , 2653.5, 5000. ]),
  array([ 623. , 2728.5, 5000. ]),
  array([ 620.5, 2987.5, 5000. ]),
  array([ 975., 2953., 5000.]),
  array([1055. , 3077.5, 5000. ]),
  array([1288., 3588., 5000.]),
  array([ 428.5, 2096.5, 5000. ])],
 [array([ 999.5, 3666.5, 5000. ]),
  array([1521.5, 3703.5, 5000. ]),
  array([ 458.5, 1463. , 3307. ]),
  array([ 840. , 2653.5, 5000. ]),
  array([ 623. , 2728.5, 5000. ]),
  array([ 620.5, 2987.5, 5000. ]),
  array([ 975., 2953., 5000.]),
  array([1055. , 3077.5, 5000. ]),
  array([1288., 3588., 5000.]),
  array([ 428.5, 2096.5, 5000. ])])